version: '3.8'
services:
  app:
    container_name: api-tray
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tray-network

  mysql:
    image: mysql:latest
    container_name: db-tray
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=TrayRetailSalesPro
      - MYSQL_USER=tray-user
      - MYSQL_PASSWORD=tray123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - tray-network

networks:
  tray-network:
    driver: bridge