version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=your-app-key
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tray-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your-mysql-root-password
      - MYSQL_DATABASE=your-database-name
      - MYSQL_USER=your-database-username
      - MYSQL_PASSWORD=your-database-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - tray-network

networks:
  tray-network:
    driver: bridge